# Generated by Django 4.2 on 2025-12-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('payee', models.CharField(blank=True, max_length=256)),
                ('tin', models.CharField(blank=True, max_length=64)),
                ('action_required', models.CharField(blank=True, max_length=64, null=True)),
                ('mode_of_payment', models.CharField(blank=True, max_length=256, null=True)),
                ('payment_for', models.CharField(blank=True, max_length=256, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('requested_by', models.CharField(blank=True, max_length=128)),
                ('checked_by', models.CharField(blank=True, max_length=128)),
                ('recommend_approval', models.CharField(blank=True, max_length=128)),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
