# Generated by Django 4.2 on 2025-12-01 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('requester', models.CharField(blank=True, max_length=128)),
                ('dept', models.CharField(blank=True, max_length=128)),
                ('date_needed', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('requested_by', models.CharField(blank=True, max_length=128)),
                ('checked_by', models.CharField(blank=True, max_length=128)),
                ('recommend_approval', models.CharField(blank=True, max_length=128)),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PRItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stk', models.CharField(blank=True, max_length=64)),
                ('qty', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('desc', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_requisitions.purchaserequisition')),
            ],
        ),
    ]
