# Generated by Django 4.2 on 2025-11-30 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('dept', models.CharField(blank=True, max_length=128)),
                ('supplier', models.CharField(blank=True, max_length=256)),
                ('tin', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=128)),
                ('contact_number', models.CharField(blank=True, max_length=64)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prepared_by', models.CharField(blank=True, max_length=128)),
                ('checked_by', models.CharField(blank=True, max_length=128)),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('requester', models.CharField(blank=True, max_length=128)),
                ('dept', models.CharField(blank=True, max_length=128)),
                ('date_needed', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('requested_by', models.CharField(blank=True, max_length=128)),
                ('checked_by', models.CharField(blank=True, max_length=128)),
                ('recommend_approval', models.CharField(blank=True, max_length=128)),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('payee', models.CharField(blank=True, max_length=256)),
                ('tin', models.CharField(blank=True, max_length=64)),
                ('action_required', models.CharField(blank=True, max_length=64, null=True)),
                ('mode_of_payment', models.CharField(blank=True, max_length=256, null=True)),
                ('payment_for', models.CharField(blank=True, max_length=256, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('requested_by', models.CharField(blank=True, max_length=128)),
                ('checked_by', models.CharField(blank=True, max_length=128)),
                ('recommend_approval', models.CharField(blank=True, max_length=128)),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PRItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stk', models.CharField(blank=True, max_length=64)),
                ('qty', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('desc', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaserequisition')),
            ],
        ),
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder')),
            ],
        ),
    ]
