# Generated by Django 4.2 on 2025-12-01 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('dept', models.CharField(blank=True, max_length=128)),
                ('supplier', models.CharField(blank=True, max_length=256)),
                ('tin', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=128)),
                ('contact_number', models.CharField(blank=True, max_length=64)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prepared_by', models.CharField(blank=True, max_length=128)),
                ('checked_by', models.CharField(blank=True, max_length=128)),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_orders.purchaseorder')),
            ],
        ),
    ]
